// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjpDqC4DrmqrS-E0L6HQEZ08MJw0cBpQ',
    appId: '1:960090436644:web:5679a7a18d22881ec614b1',
    messagingSenderId: '960090436644',
    projectId: 'miaged-a561b',
    authDomain: 'miaged-a561b.firebaseapp.com',
    storageBucket: 'miaged-a561b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8SMA5BlrD-G2XKL6kQydSJjKe8sAXhw8',
    appId: '1:960090436644:android:7b961a8426244769c614b1',
    messagingSenderId: '960090436644',
    projectId: 'miaged-a561b',
    storageBucket: 'miaged-a561b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrp6fm_zipLw2t4Pn8RmPCygRzGCPc69M',
    appId: '1:960090436644:ios:a7b3479931dda92ec614b1',
    messagingSenderId: '960090436644',
    projectId: 'miaged-a561b',
    storageBucket: 'miaged-a561b.appspot.com',
    iosClientId: '960090436644-79n3f16bth2bi6la6u5mehgjj4qfs3jn.apps.googleusercontent.com',
    iosBundleId: 'com.miaged.miaged',
  );
}
